version: '3.8'

services:
  db:
    image: nouchka/sqlite3:latest
    container_name: sqlite_db
    volumes:
      - sqlite_data:/root/db
    command: ["sqlite3", "/root/db/database.db"]

  app:
    build: ./app
    container_name: flask_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:////root/db/database.db
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/root/db
    networks:
      - app_network

volumes:
  sqlite_data:
    driver: local

networks:
  app_network:
    driver: bridge